services:
  postgres-master:
    image: postgres:18.3
    container_name: hl_postgres_master
    restart: unless-stopped
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_user -d social"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    networks:
      - pgcluster

  postgres-slave1:
    image: postgres:18.3
    container_name: hl_postgres_slave1
    restart: unless-stopped
    environment:
      PGPASSWORD: replicator_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata_slave1:/var/lib/postgresql/data
      - ./db/slave/postgresql.conf:/etc/postgresql/postgresql.conf
    depends_on:
      postgres-master:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "
        set -e
        if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
          echo 'Waiting for master to accept replication connections...'
          until pg_isready -h postgres-master -p 5432 -U replicator -d social; do
            sleep 2
          done
          sleep 3
          echo 'Creating base backup from master...'
          chown -R postgres:postgres /var/lib/postgresql/data
          gosu postgres pg_basebackup -h postgres-master -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R           -S slave1_slot
          chmod 700 /var/lib/postgresql/data
        fi
        exec gosu postgres postgres -D /var/lib/postgresql/data -c config_file=/etc/postgresql/postgresql.conf
      "
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    networks:
      - pgcluster

  postgres-slave2:
    image: postgres:18.3
    container_name: hl_postgres_slave2
    restart: unless-stopped
    environment:
      PGPASSWORD: replicator_pass
    ports:
      - "5434:5432"
    volumes:
      - pgdata_slave2:/var/lib/postgresql/data
      - ./db/slave/postgresql.conf:/etc/postgresql/postgresql.conf
    depends_on:
      postgres-master:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "
        set -e
        if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
          echo 'Waiting for master to accept replication connections...'
          until pg_isready -h postgres-master -p 5432 -U replicator -d social; do
            sleep 2
          done
          sleep 3
          echo 'Creating base backup from master...'
          chown -R postgres:postgres /var/lib/postgresql/data
          gosu postgres pg_basebackup -h postgres-master -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R           -S slave2_slot
          chmod 700 /var/lib/postgresql/data
        fi
        exec gosu postgres postgres -D /var/lib/postgresql/data -c config_file=/etc/postgresql/postgresql.conf
      "
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    networks:
      - pgcluster

  redis:
    image: redis:7-alpine
    container_name: hl_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pgcluster

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: hl_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pgcluster

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: hl_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - pgcluster

  app:
    build: .
    container_name: hl_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres-master
      DB_PORT: 5432
      DB_NAME: social
      DB_USER: social_user
      DB_PASSWORD: social_pass
      DB_REPLICA_HOSTS: "postgres-slave1:5432,postgres-slave2:5432"
      JWT_SECRET: change-me-secret
      SERVER_ADDR: :8080
      REDIS_ADDR: redis:6379
      KAFKA_BROKERS: kafka:29092
      LOG_LEVEL: debug
    depends_on:
      postgres-master:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - pgcluster

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pgcluster

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - pgcluster

volumes:
  pgdata:
    name: highload-homework3_pgdata
  pgdata_slave1:
    name: highload-homework3_pgdata_slave1
  pgdata_slave2:
    name: highload-homework3_pgdata_slave2

networks:
  pgcluster:
    driver: bridge