# Master PostgreSQL Configuration for Streaming Replication

listen_addresses = '*'
port = 5432

# Replication settings
ssl = off
wal_level = replica
max_wal_senders = 10
wal_keep_size = 256MB
max_replication_slots = 10
hot_standby = on

# Shared Preload Libraries
shared_preload_libraries = ''

# Resource Consumption
max_connections = 100

# Write-Ahead Log
wal_log_hints = on